# See documentation: https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html
# Version bundle 3.0
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'